// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: cc/cc.proto

package cc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_NOACCESS Role = 0
	Role_USER     Role = 1
	Role_OWNER    Role = 2
	Role_ADMIN    Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "NOACCESS",
		1: "USER",
		2: "OWNER",
		3: "ADMIN",
	}
	Role_value = map[string]int32{
		"NOACCESS": 0,
		"USER":     1,
		"OWNER":    2,
		"ADMIN":    3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_cc_cc_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_cc_cc_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_NEW               Status = 0
	Status_OPEN              Status = 1
	Status_RESOLVE           Status = 2
	Status_CLOSE             Status = 3
	Status_ANSWERED          Status = 4
	Status_CUSTOMER_REPLY    Status = 5
	Status_WAITING_FOR_REPLY Status = 6
	Status_ON_HOLD           Status = 7
	Status_IN_PROGRESS       Status = 8
	// ONBOARDING is an outreach ticket: we wrote first, nobody asked. It is the
	// one status a message does not change (see MessagesAPI.Send), so a campaign
	// of thousands does not walk through the operators' status board on its way
	// to being closed. Set only at creation, and only deliberately; it leaves
	// the ticket the way any other does, by someone closing it.
	Status_ONBOARDING Status = 9
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "NEW",
		1: "OPEN",
		2: "RESOLVE",
		3: "CLOSE",
		4: "ANSWERED",
		5: "CUSTOMER_REPLY",
		6: "WAITING_FOR_REPLY",
		7: "ON_HOLD",
		8: "IN_PROGRESS",
		9: "ONBOARDING",
	}
	Status_value = map[string]int32{
		"NEW":               0,
		"OPEN":              1,
		"RESOLVE":           2,
		"CLOSE":             3,
		"ANSWERED":          4,
		"CUSTOMER_REPLY":    5,
		"WAITING_FOR_REPLY": 6,
		"ON_HOLD":           7,
		"IN_PROGRESS":       8,
		"ONBOARDING":        9,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cc_cc_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_cc_cc_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{1}
}

type Kind int32

const (
	Kind_DEFAULT Kind = 0
	// ADMIN_ONLY is a note humans leave for each other about the chat. The
	// customer never sees it; nothing answers it.
	Kind_ADMIN_ONLY Kind = 1
	Kind_FOR_BOT    Kind = 2
	// COPILOT is the operator's conversation WITH the AI assistant about this
	// chat. Same visibility as ADMIN_ONLY - admins only - but a separate lane,
	// because the two were one and the notes operators wrote to each other kept
	// waking the bot, while the bot's answers filled the notes.
	Kind_COPILOT Kind = 3
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "DEFAULT",
		1: "ADMIN_ONLY",
		2: "FOR_BOT",
		3: "COPILOT",
	}
	Kind_value = map[string]int32{
		"DEFAULT":    0,
		"ADMIN_ONLY": 1,
		"FOR_BOT":    2,
		"COPILOT":    3,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_cc_cc_proto_enumTypes[2].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_cc_cc_proto_enumTypes[2]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{2}
}

type EventType int32

const (
	EventType_PING                    EventType = 0
	EventType_CHAT_CREATED            EventType = 1
	EventType_CHAT_UPDATED            EventType = 2
	EventType_CHAT_DELETED            EventType = 3
	EventType_CHAT_READ               EventType = 4
	EventType_MESSAGE_SENT            EventType = 5
	EventType_MESSAGE_UPDATED         EventType = 6
	EventType_MESSAGE_DELETED         EventType = 7
	EventType_CHAT_DEPARTMENT_CHANGED EventType = 8
	EventType_CHAT_STATUS_CHANGED     EventType = 9
	EventType_CHATS_MERGED            EventType = 10
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "PING",
		1:  "CHAT_CREATED",
		2:  "CHAT_UPDATED",
		3:  "CHAT_DELETED",
		4:  "CHAT_READ",
		5:  "MESSAGE_SENT",
		6:  "MESSAGE_UPDATED",
		7:  "MESSAGE_DELETED",
		8:  "CHAT_DEPARTMENT_CHANGED",
		9:  "CHAT_STATUS_CHANGED",
		10: "CHATS_MERGED",
	}
	EventType_value = map[string]int32{
		"PING":                    0,
		"CHAT_CREATED":            1,
		"CHAT_UPDATED":            2,
		"CHAT_DELETED":            3,
		"CHAT_READ":               4,
		"MESSAGE_SENT":            5,
		"MESSAGE_UPDATED":         6,
		"MESSAGE_DELETED":         7,
		"CHAT_DEPARTMENT_CHANGED": 8,
		"CHAT_STATUS_CHANGED":     9,
		"CHATS_MERGED":            10,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_cc_cc_proto_enumTypes[3].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_cc_cc_proto_enumTypes[3]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{3}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cc_cc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{0}
}

type ChatMeta struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Unread        int32                      `protobuf:"varint,1,opt,name=unread,proto3" json:"unread,omitempty"`
	FirstMessage  *Message                   `protobuf:"bytes,2,opt,name=first_message,json=firstMessage,proto3" json:"first_message,omitempty"`
	LastMessage   *Message                   `protobuf:"bytes,3,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	Data          map[string]*structpb.Value `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMeta) Reset() {
	*x = ChatMeta{}
	mi := &file_cc_cc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMeta) ProtoMessage() {}

func (x *ChatMeta) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMeta.ProtoReflect.Descriptor instead.
func (*ChatMeta) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMeta) GetUnread() int32 {
	if x != nil {
		return x.Unread
	}
	return 0
}

func (x *ChatMeta) GetFirstMessage() *Message {
	if x != nil {
		return x.FirstMessage
	}
	return nil
}

func (x *ChatMeta) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *ChatMeta) GetData() map[string]*structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

type Chat struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Uuid          string                     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Users         []string                   `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Admins        []string                   `protobuf:"bytes,3,rep,name=admins,proto3" json:"admins,omitempty"`
	Owner         string                     `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Gateways      []string                   `protobuf:"bytes,5,rep,name=gateways,proto3" json:"gateways,omitempty"`
	Role          Role                       `protobuf:"varint,6,opt,name=role,proto3,enum=cc.Role" json:"role,omitempty"`
	Topic         *string                    `protobuf:"bytes,7,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	Meta          *ChatMeta                  `protobuf:"bytes,8,opt,name=meta,proto3,oneof" json:"meta,omitempty"`
	Created       int64                      `protobuf:"varint,9,opt,name=created,proto3" json:"created,omitempty"`
	Status        Status                     `protobuf:"varint,10,opt,name=status,proto3,enum=cc.Status" json:"status,omitempty"`
	Department    string                     `protobuf:"bytes,11,opt,name=department,proto3" json:"department,omitempty"`
	Responsible   *string                    `protobuf:"bytes,12,opt,name=responsible,proto3,oneof" json:"responsible,omitempty"`
	BotState      map[string]*structpb.Value `protobuf:"bytes,13,rep,name=bot_state,json=botState,proto3" json:"bot_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_cc_cc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{2}
}

func (x *Chat) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Chat) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Chat) GetAdmins() []string {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *Chat) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Chat) GetGateways() []string {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *Chat) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_NOACCESS
}

func (x *Chat) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

func (x *Chat) GetMeta() *ChatMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Chat) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Chat) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_NEW
}

func (x *Chat) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Chat) GetResponsible() string {
	if x != nil && x.Responsible != nil {
		return *x.Responsible
	}
	return ""
}

func (x *Chat) GetBotState() map[string]*structpb.Value {
	if x != nil {
		return x.BotState
	}
	return nil
}

type Chats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chats) Reset() {
	*x = Chats{}
	mi := &file_cc_cc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chats) ProtoMessage() {}

func (x *Chats) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chats.ProtoReflect.Descriptor instead.
func (*Chats) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{3}
}

func (x *Chats) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type Merge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []string               `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merge) Reset() {
	*x = Merge{}
	mi := &file_cc_cc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merge) ProtoMessage() {}

func (x *Merge) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merge.ProtoReflect.Descriptor instead.
func (*Merge) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{4}
}

func (x *Merge) GetChats() []string {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ListChatsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Page          *uint64                    `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit         *uint64                    `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Field         *string                    `protobuf:"bytes,3,opt,name=field,proto3,oneof" json:"field,omitempty"` // Sort field
	Sort          *string                    `protobuf:"bytes,4,opt,name=sort,proto3,oneof" json:"sort,omitempty"`   // Sort direction
	Filters       map[string]*structpb.Value `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsRequest) Reset() {
	*x = ListChatsRequest{}
	mi := &file_cc_cc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsRequest) ProtoMessage() {}

func (x *ListChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsRequest.ProtoReflect.Descriptor instead.
func (*ListChatsRequest) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{5}
}

func (x *ListChatsRequest) GetPage() uint64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListChatsRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListChatsRequest) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

func (x *ListChatsRequest) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

func (x *ListChatsRequest) GetFilters() map[string]*structpb.Value {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SetBotStateRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Chat          string                     `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	State         map[string]*structpb.Value `protobuf:"bytes,2,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Disabled      *bool                      `protobuf:"varint,3,opt,name=disabled,proto3,oneof" json:"disabled,omitempty"`
	Escalated     *bool                      `protobuf:"varint,4,opt,name=escalated,proto3,oneof" json:"escalated,omitempty"`
	SkipReview    *bool                      `protobuf:"varint,5,opt,name=skip_review,json=skipReview,proto3,oneof" json:"skip_review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBotStateRequest) Reset() {
	*x = SetBotStateRequest{}
	mi := &file_cc_cc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBotStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBotStateRequest) ProtoMessage() {}

func (x *SetBotStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBotStateRequest.ProtoReflect.Descriptor instead.
func (*SetBotStateRequest) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{6}
}

func (x *SetBotStateRequest) GetChat() string {
	if x != nil {
		return x.Chat
	}
	return ""
}

func (x *SetBotStateRequest) GetState() map[string]*structpb.Value {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SetBotStateRequest) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

func (x *SetBotStateRequest) GetEscalated() bool {
	if x != nil && x.Escalated != nil {
		return *x.Escalated
	}
	return false
}

func (x *SetBotStateRequest) GetSkipReview() bool {
	if x != nil && x.SkipReview != nil {
		return *x.SkipReview
	}
	return false
}

type ListChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          []*Chat                `protobuf:"bytes,1,rep,name=pool,proto3" json:"pool,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsResponse) Reset() {
	*x = ListChatsResponse{}
	mi := &file_cc_cc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsResponse) ProtoMessage() {}

func (x *ListChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsResponse.ProtoReflect.Descriptor instead.
func (*ListChatsResponse) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{7}
}

func (x *ListChatsResponse) GetPool() []*Chat {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *ListChatsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CountChatsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Filters       map[string]*structpb.Value `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountChatsRequest) Reset() {
	*x = CountChatsRequest{}
	mi := &file_cc_cc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountChatsRequest) ProtoMessage() {}

func (x *CountChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountChatsRequest.ProtoReflect.Descriptor instead.
func (*CountChatsRequest) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{8}
}

func (x *CountChatsRequest) GetFilters() map[string]*structpb.Value {
	if x != nil {
		return x.Filters
	}
	return nil
}

type CountChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      map[int32]int64        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountChatsResponse) Reset() {
	*x = CountChatsResponse{}
	mi := &file_cc_cc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountChatsResponse) ProtoMessage() {}

func (x *CountChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountChatsResponse.ProtoReflect.Descriptor instead.
func (*CountChatsResponse) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{9}
}

func (x *CountChatsResponse) GetStatuses() map[int32]int64 {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_cc_cc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{10}
}

func (x *Attachment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Attachment) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// PollOption is one answer to pick.
//
// The id is what a vote refers to, never the label or the position: editing
// the wording of an option afterwards must not silently move everybody who
// already answered onto a different answer.
type PollOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollOption) Reset() {
	*x = PollOption{}
	mi := &file_cc_cc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollOption) ProtoMessage() {}

func (x *PollOption) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollOption.ProtoReflect.Descriptor instead.
func (*PollOption) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{11}
}

func (x *PollOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PollOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// PollVote is one person's answer.
type PollVote struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Options []string               `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"` // option ids
	Ts      int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	// message is the ordinary chat message that states this answer in words.
	//
	// Kept here so that changing an answer edits that message instead of posting
	// another one: a poll answered four times would otherwise read as four
	// replies, and an operator would have to work out which one still counts.
	// Empty for answers recorded before this was kept.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollVote) Reset() {
	*x = PollVote{}
	mi := &file_cc_cc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollVote) ProtoMessage() {}

func (x *PollVote) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollVote.ProtoReflect.Descriptor instead.
func (*PollVote) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{12}
}

func (x *PollVote) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PollVote) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *PollVote) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Poll turns a message into a question with answers to click, instead of a
// list of options typed into the text and an answer typed back.
//
// It is a field of an ordinary message, not a kind of its own: everything that
// already carries a message — the event stream, the gateways, the WHMCS sync,
// read receipts — carries a poll without knowing anything about polls. A
// client that has not been taught about them shows the question and nothing
// else, which is why gateway and WHMCS events get the options appended to
// their text copy (see pkg/pubsub): a person on telegram or email still sees
// what there was to answer and can reply in words.
type Poll struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// question is optional: usually the message text is the question, and this
	// is left empty.
	Question string        `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Options  []*PollOption `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	// multiple allows more than one answer at a time.
	Multiple bool `protobuf:"varint,3,opt,name=multiple,proto3" json:"multiple,omitempty"`
	// closed stops accepting answers. The answers already given stay visible.
	Closed bool `protobuf:"varint,4,opt,name=closed,proto3" json:"closed,omitempty"`
	// votes is keyed by account uuid. A ticket has one customer, so this is
	// normally a single entry — the point is knowing *who* answered *what*, not
	// a tally.
	Votes         map[string]*PollVote `protobuf:"bytes,5,rep,name=votes,proto3" json:"votes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poll) Reset() {
	*x = Poll{}
	mi := &file_cc_cc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poll.ProtoReflect.Descriptor instead.
func (*Poll) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{13}
}

func (x *Poll) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Poll) GetOptions() []*PollOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Poll) GetMultiple() bool {
	if x != nil {
		return x.Multiple
	}
	return false
}

func (x *Poll) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *Poll) GetVotes() map[string]*PollVote {
	if x != nil {
		return x.Votes
	}
	return nil
}

// VoteRequest answers a poll. An empty options list retracts the answer.
type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"` // option ids
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_cc_cc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{14}
}

func (x *VoteRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VoteRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type Message struct {
	state       protoimpl.MessageState     `protogen:"open.v1"`
	Uuid        string                     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Kind        Kind                       `protobuf:"varint,2,opt,name=kind,proto3,enum=cc.Kind" json:"kind,omitempty"`
	Sender      string                     `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Content     string                     `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Attachments []string                   `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Gateways    []string                   `protobuf:"bytes,6,rep,name=gateways,proto3" json:"gateways,omitempty"`
	Chat        *string                    `protobuf:"bytes,7,opt,name=chat,proto3,oneof" json:"chat,omitempty"` // Required for Send, Update and Delete requests
	Sent        int64                      `protobuf:"varint,8,opt,name=sent,proto3" json:"sent,omitempty"`
	Edited      int64                      `protobuf:"varint,9,opt,name=edited,proto3" json:"edited,omitempty"`
	UnderReview bool                       `protobuf:"varint,10,opt,name=under_review,json=underReview,proto3" json:"under_review,omitempty"`
	Readers     []string                   `protobuf:"bytes,11,rep,name=readers,proto3" json:"readers,omitempty"`
	Meta        map[string]*structpb.Value `protobuf:"bytes,12,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Mentioned   []string                   `protobuf:"bytes,13,rep,name=mentioned,proto3" json:"mentioned,omitempty"`
	// poll is set on the few messages that ask something with buttons.
	Poll          *Poll `protobuf:"bytes,14,opt,name=poll,proto3,oneof" json:"poll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_cc_cc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{15}
}

func (x *Message) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Message) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_DEFAULT
}

func (x *Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Message) GetGateways() []string {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *Message) GetChat() string {
	if x != nil && x.Chat != nil {
		return *x.Chat
	}
	return ""
}

func (x *Message) GetSent() int64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *Message) GetEdited() int64 {
	if x != nil {
		return x.Edited
	}
	return 0
}

func (x *Message) GetUnderReview() bool {
	if x != nil {
		return x.UnderReview
	}
	return false
}

func (x *Message) GetReaders() []string {
	if x != nil {
		return x.Readers
	}
	return nil
}

func (x *Message) GetMeta() map[string]*structpb.Value {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Message) GetMentioned() []string {
	if x != nil {
		return x.Mentioned
	}
	return nil
}

func (x *Message) GetPoll() *Poll {
	if x != nil {
		return x.Poll
	}
	return nil
}

type Messages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Messages) Reset() {
	*x = Messages{}
	mi := &file_cc_cc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messages) ProtoMessage() {}

func (x *Messages) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messages.ProtoReflect.Descriptor instead.
func (*Messages) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{16}
}

func (x *Messages) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MessagesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesListRequest) Reset() {
	*x = MessagesListRequest{}
	mi := &file_cc_cc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesListRequest) ProtoMessage() {}

func (x *MessagesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesListRequest.ProtoReflect.Descriptor instead.
func (*MessagesListRequest) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{17}
}

// PollsRequest asks for specific messages by uuid, to read the answers off
// their polls.
type PollsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollsRequest) Reset() {
	*x = PollsRequest{}
	mi := &file_cc_cc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollsRequest) ProtoMessage() {}

func (x *PollsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollsRequest.ProtoReflect.Descriptor instead.
func (*PollsRequest) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{18}
}

func (x *PollsRequest) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CcIsBot       bool                   `protobuf:"varint,4,opt,name=cc_is_bot,json=ccIsBot,proto3" json:"cc_is_bot,omitempty"`
	CcUsername    string                 `protobuf:"bytes,5,opt,name=cc_username,json=ccUsername,proto3" json:"cc_username,omitempty"`
	CcCommands    map[string]string      `protobuf:"bytes,6,rep,name=cc_commands,json=ccCommands,proto3" json:"cc_commands,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_cc_cc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{19}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *User) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *User) GetCcIsBot() bool {
	if x != nil {
		return x.CcIsBot
	}
	return false
}

func (x *User) GetCcUsername() string {
	if x != nil {
		return x.CcUsername
	}
	return ""
}

func (x *User) GetCcCommands() map[string]string {
	if x != nil {
		return x.CcCommands
	}
	return nil
}

type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Admins        []string               `protobuf:"bytes,4,rep,name=admins,proto3" json:"admins,omitempty"`
	Public        bool                   `protobuf:"varint,5,opt,name=public,proto3" json:"public,omitempty"`
	WhmcsId       *string                `protobuf:"bytes,6,opt,name=whmcs_id,json=whmcsId,proto3,oneof" json:"whmcs_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_cc_cc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{20}
}

func (x *Department) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Department) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Department) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Department) GetAdmins() []string {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *Department) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *Department) GetWhmcsId() string {
	if x != nil && x.WhmcsId != nil {
		return *x.WhmcsId
	}
	return ""
}

type Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_cc_cc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{21}
}

func (x *Option) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Option) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Options       []*Option              `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_cc_cc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{22}
}

func (x *Metric) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Metric) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

type Defaults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []string               `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	Admins        []string               `protobuf:"bytes,2,rep,name=admins,proto3" json:"admins,omitempty"`
	Departments   []*Department          `protobuf:"bytes,3,rep,name=departments,proto3" json:"departments,omitempty"`
	Metrics       map[string]*Metric     `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Templates     map[string]string      `protobuf:"bytes,5,rep,name=templates,proto3" json:"templates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bot           *Bot                   `protobuf:"bytes,6,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Defaults) Reset() {
	*x = Defaults{}
	mi := &file_cc_cc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Defaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Defaults) ProtoMessage() {}

func (x *Defaults) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Defaults.ProtoReflect.Descriptor instead.
func (*Defaults) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{23}
}

func (x *Defaults) GetGateways() []string {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *Defaults) GetAdmins() []string {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *Defaults) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

func (x *Defaults) GetMetrics() map[string]*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Defaults) GetTemplates() map[string]string {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *Defaults) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

type Bot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                           // Bot's prompt.
	Review        bool                   `protobuf:"varint,2,opt,name=review,proto3" json:"review,omitempty"`                                                                          // If bot's messages always under review.
	Enable        bool                   `protobuf:"varint,3,opt,name=enable,proto3" json:"enable,omitempty"`                                                                          // If bot enabled or disabled in new chats.
	Values        map[string]string      `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom key-value variables for bot's prompt (prompt field). Use it like this in prompt - {VALUE_KEY}
	Initiator     bool                   `protobuf:"varint,5,opt,name=initiator,proto3" json:"initiator,omitempty"`                                                                    // If bot's FIRST message ignoring 'review' state. That means bot ALWAYS sends his first message no matter what.
	Emergency     bool                   `protobuf:"varint,6,opt,name=emergency,proto3" json:"emergency,omitempty"`                                                                    // True - If some emergency situation happens. Bot should check this state and base his response on this field.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bot) Reset() {
	*x = Bot{}
	mi := &file_cc_cc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{24}
}

func (x *Bot) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Bot) GetReview() bool {
	if x != nil {
		return x.Review
	}
	return false
}

func (x *Bot) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Bot) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Bot) GetInitiator() bool {
	if x != nil {
		return x.Initiator
	}
	return false
}

func (x *Bot) GetEmergency() bool {
	if x != nil {
		return x.Emergency
	}
	return false
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_cc_cc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{25}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Users) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type FetchDefaultsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FetchTemplates bool                   `protobuf:"varint,1,opt,name=fetch_templates,json=fetchTemplates,proto3" json:"fetch_templates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchDefaultsRequest) Reset() {
	*x = FetchDefaultsRequest{}
	mi := &file_cc_cc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDefaultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDefaultsRequest) ProtoMessage() {}

func (x *FetchDefaultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDefaultsRequest.ProtoReflect.Descriptor instead.
func (*FetchDefaultsRequest) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{26}
}

func (x *FetchDefaultsRequest) GetFetchTemplates() bool {
	if x != nil {
		return x.FetchTemplates
	}
	return false
}

type GetMembersRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Uuids         []string                   `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	Page          *uint64                    `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit         *uint64                    `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Field         *string                    `protobuf:"bytes,4,opt,name=field,proto3,oneof" json:"field,omitempty"` // Sort field
	Sort          *string                    `protobuf:"bytes,5,opt,name=sort,proto3,oneof" json:"sort,omitempty"`   // Sort direction
	Filters       map[string]*structpb.Value `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	mi := &file_cc_cc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{27}
}

func (x *GetMembersRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *GetMembersRequest) GetPage() uint64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetMembersRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetMembersRequest) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

func (x *GetMembersRequest) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

func (x *GetMembersRequest) GetFilters() map[string]*structpb.Value {
	if x != nil {
		return x.Filters
	}
	return nil
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=cc.EventType" json:"type,omitempty"`
	// Types that are valid to be assigned to Item:
	//
	//	*Event_Chat
	//	*Event_Msg
	Item          isEvent_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_cc_cc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{28}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_PING
}

func (x *Event) GetItem() isEvent_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *Event) GetChat() *Chat {
	if x != nil {
		if x, ok := x.Item.(*Event_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Event) GetMsg() *Message {
	if x != nil {
		if x, ok := x.Item.(*Event_Msg); ok {
			return x.Msg
		}
	}
	return nil
}

type isEvent_Item interface {
	isEvent_Item()
}

type Event_Chat struct {
	Chat *Chat `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type Event_Msg struct {
	Msg *Message `protobuf:"bytes,3,opt,name=msg,proto3,oneof"`
}

func (*Event_Chat) isEvent_Item() {}

func (*Event_Msg) isEvent_Item() {}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      map[string]string      `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_cc_cc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cc_cc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_cc_cc_proto_rawDescGZIP(), []int{29}
}

func (x *StreamRequest) GetCommands() map[string]string {
	if x != nil {
		return x.Commands
	}
	return nil
}

var File_cc_cc_proto protoreflect.FileDescriptor

const file_cc_cc_proto_rawDesc = "" +
	"\n" +
	"\vcc/cc.proto\x12\x02cc\x1a\x1cgoogle/protobuf/struct.proto\"\a\n" +
	"\x05Empty\"\x81\x02\n" +
	"\bChatMeta\x12\x16\n" +
	"\x06unread\x18\x01 \x01(\x05R\x06unread\x120\n" +
	"\rfirst_message\x18\x02 \x01(\v2\v.cc.MessageR\ffirstMessage\x12.\n" +
	"\flast_message\x18\x03 \x01(\v2\v.cc.MessageR\vlastMessage\x12*\n" +
	"\x04data\x18\x04 \x03(\v2\x16.cc.ChatMeta.DataEntryR\x04data\x1aO\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x8c\x04\n" +
	"\x04Chat\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05users\x18\x02 \x03(\tR\x05users\x12\x16\n" +
	"\x06admins\x18\x03 \x03(\tR\x06admins\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x1a\n" +
	"\bgateways\x18\x05 \x03(\tR\bgateways\x12\x1c\n" +
	"\x04role\x18\x06 \x01(\x0e2\b.cc.RoleR\x04role\x12\x19\n" +
	"\x05topic\x18\a \x01(\tH\x00R\x05topic\x88\x01\x01\x12%\n" +
	"\x04meta\x18\b \x01(\v2\f.cc.ChatMetaH\x01R\x04meta\x88\x01\x01\x12\x18\n" +
	"\acreated\x18\t \x01(\x03R\acreated\x12\"\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\n" +
	".cc.StatusR\x06status\x12\x1e\n" +
	"\n" +
	"department\x18\v \x01(\tR\n" +
	"department\x12%\n" +
	"\vresponsible\x18\f \x01(\tH\x02R\vresponsible\x88\x01\x01\x123\n" +
	"\tbot_state\x18\r \x03(\v2\x16.cc.Chat.BotStateEntryR\bbotState\x1aS\n" +
	"\rBotStateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\b\n" +
	"\x06_topicB\a\n" +
	"\x05_metaB\x0e\n" +
	"\f_responsible\"'\n" +
	"\x05Chats\x12\x1e\n" +
	"\x05chats\x18\x01 \x03(\v2\b.cc.ChatR\x05chats\"\x1d\n" +
	"\x05Merge\x12\x14\n" +
	"\x05chats\x18\x01 \x03(\tR\x05chats\"\xb1\x02\n" +
	"\x10ListChatsRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x04H\x00R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x04H\x01R\x05limit\x88\x01\x01\x12\x19\n" +
	"\x05field\x18\x03 \x01(\tH\x02R\x05field\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x04 \x01(\tH\x03R\x04sort\x88\x01\x01\x12;\n" +
	"\afilters\x18\x05 \x03(\v2!.cc.ListChatsRequest.FiltersEntryR\afilters\x1aR\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\a\n" +
	"\x05_pageB\b\n" +
	"\x06_limitB\b\n" +
	"\x06_fieldB\a\n" +
	"\x05_sort\"\xc8\x02\n" +
	"\x12SetBotStateRequest\x12\x12\n" +
	"\x04chat\x18\x01 \x01(\tR\x04chat\x127\n" +
	"\x05state\x18\x02 \x03(\v2!.cc.SetBotStateRequest.StateEntryR\x05state\x12\x1f\n" +
	"\bdisabled\x18\x03 \x01(\bH\x00R\bdisabled\x88\x01\x01\x12!\n" +
	"\tescalated\x18\x04 \x01(\bH\x01R\tescalated\x88\x01\x01\x12$\n" +
	"\vskip_review\x18\x05 \x01(\bH\x02R\n" +
	"skipReview\x88\x01\x01\x1aP\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\v\n" +
	"\t_disabledB\f\n" +
	"\n" +
	"_escalatedB\x0e\n" +
	"\f_skip_review\"G\n" +
	"\x11ListChatsResponse\x12\x1c\n" +
	"\x04pool\x18\x01 \x03(\v2\b.cc.ChatR\x04pool\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa5\x01\n" +
	"\x11CountChatsRequest\x12<\n" +
	"\afilters\x18\x01 \x03(\v2\".cc.CountChatsRequest.FiltersEntryR\afilters\x1aR\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x93\x01\n" +
	"\x12CountChatsResponse\x12@\n" +
	"\bstatuses\x18\x01 \x03(\v2$.cc.CountChatsResponse.StatusesEntryR\bstatuses\x1a;\n" +
	"\rStatusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\":\n" +
	"\n" +
	"Attachment\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"2\n" +
	"\n" +
	"PollOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"N\n" +
	"\bPollVote\x12\x18\n" +
	"\aoptions\x18\x01 \x03(\tR\aoptions\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xf3\x01\n" +
	"\x04Poll\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12(\n" +
	"\aoptions\x18\x02 \x03(\v2\x0e.cc.PollOptionR\aoptions\x12\x1a\n" +
	"\bmultiple\x18\x03 \x01(\bR\bmultiple\x12\x16\n" +
	"\x06closed\x18\x04 \x01(\bR\x06closed\x12)\n" +
	"\x05votes\x18\x05 \x03(\v2\x13.cc.Poll.VotesEntryR\x05votes\x1aF\n" +
	"\n" +
	"VotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.cc.PollVoteR\x05value:\x028\x01\"A\n" +
	"\vVoteRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\"\xfc\x03\n" +
	"\aMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\x04kind\x18\x02 \x01(\x0e2\b.cc.KindR\x04kind\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12 \n" +
	"\vattachments\x18\x05 \x03(\tR\vattachments\x12\x1a\n" +
	"\bgateways\x18\x06 \x03(\tR\bgateways\x12\x17\n" +
	"\x04chat\x18\a \x01(\tH\x00R\x04chat\x88\x01\x01\x12\x12\n" +
	"\x04sent\x18\b \x01(\x03R\x04sent\x12\x16\n" +
	"\x06edited\x18\t \x01(\x03R\x06edited\x12!\n" +
	"\funder_review\x18\n" +
	" \x01(\bR\vunderReview\x12\x18\n" +
	"\areaders\x18\v \x03(\tR\areaders\x12)\n" +
	"\x04meta\x18\f \x03(\v2\x15.cc.Message.MetaEntryR\x04meta\x12\x1c\n" +
	"\tmentioned\x18\r \x03(\tR\tmentioned\x12!\n" +
	"\x04poll\x18\x0e \x01(\v2\b.cc.PollH\x01R\x04poll\x88\x01\x01\x1aO\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\a\n" +
	"\x05_chatB\a\n" +
	"\x05_poll\"3\n" +
	"\bMessages\x12'\n" +
	"\bmessages\x18\x01 \x03(\v2\v.cc.MessageR\bmessages\"\x15\n" +
	"\x13MessagesListRequest\"*\n" +
	"\fPollsRequest\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages\"\x94\x02\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x1a\n" +
	"\tcc_is_bot\x18\x04 \x01(\bR\accIsBot\x12\x1f\n" +
	"\vcc_username\x18\x05 \x01(\tR\n" +
	"ccUsername\x129\n" +
	"\vcc_commands\x18\x06 \x03(\v2\x18.cc.User.CcCommandsEntryR\n" +
	"ccCommands\x1a=\n" +
	"\x0fCcCommandsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\n" +
	"Department\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06admins\x18\x04 \x03(\tR\x06admins\x12\x16\n" +
	"\x06public\x18\x05 \x01(\bR\x06public\x12\x1e\n" +
	"\bwhmcs_id\x18\x06 \x01(\tH\x00R\awhmcsId\x88\x01\x01B\v\n" +
	"\t_whmcs_id\"0\n" +
	"\x06Option\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\"D\n" +
	"\x06Metric\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12$\n" +
	"\aoptions\x18\x02 \x03(\v2\n" +
	".cc.OptionR\aoptions\"\x81\x03\n" +
	"\bDefaults\x12\x1a\n" +
	"\bgateways\x18\x01 \x03(\tR\bgateways\x12\x16\n" +
	"\x06admins\x18\x02 \x03(\tR\x06admins\x120\n" +
	"\vdepartments\x18\x03 \x03(\v2\x0e.cc.DepartmentR\vdepartments\x123\n" +
	"\ametrics\x18\x04 \x03(\v2\x19.cc.Defaults.MetricsEntryR\ametrics\x129\n" +
	"\ttemplates\x18\x05 \x03(\v2\x1b.cc.Defaults.TemplatesEntryR\ttemplates\x12\x19\n" +
	"\x03bot\x18\x06 \x01(\v2\a.cc.BotR\x03bot\x1aF\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".cc.MetricR\x05value:\x028\x01\x1a<\n" +
	"\x0eTemplatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\x03Bot\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06review\x18\x02 \x01(\bR\x06review\x12\x16\n" +
	"\x06enable\x18\x03 \x01(\bR\x06enable\x12+\n" +
	"\x06values\x18\x04 \x03(\v2\x13.cc.Bot.ValuesEntryR\x06values\x12\x1c\n" +
	"\tinitiator\x18\x05 \x01(\bR\tinitiator\x12\x1c\n" +
	"\temergency\x18\x06 \x01(\bR\temergency\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x05Users\x12\x1e\n" +
	"\x05users\x18\x01 \x03(\v2\b.cc.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"?\n" +
	"\x14FetchDefaultsRequest\x12'\n" +
	"\x0ffetch_templates\x18\x01 \x01(\bR\x0efetchTemplates\"\xc9\x02\n" +
	"\x11GetMembersRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\x12\x17\n" +
	"\x04page\x18\x02 \x01(\x04H\x00R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x04H\x01R\x05limit\x88\x01\x01\x12\x19\n" +
	"\x05field\x18\x04 \x01(\tH\x02R\x05field\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x05 \x01(\tH\x03R\x04sort\x88\x01\x01\x12<\n" +
	"\afilters\x18\x06 \x03(\v2\".cc.GetMembersRequest.FiltersEntryR\afilters\x1aR\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\a\n" +
	"\x05_pageB\b\n" +
	"\x06_limitB\b\n" +
	"\x06_fieldB\a\n" +
	"\x05_sort\"s\n" +
	"\x05Event\x12!\n" +
	"\x04type\x18\x01 \x01(\x0e2\r.cc.EventTypeR\x04type\x12\x1e\n" +
	"\x04chat\x18\x02 \x01(\v2\b.cc.ChatH\x00R\x04chat\x12\x1f\n" +
	"\x03msg\x18\x03 \x01(\v2\v.cc.MessageH\x00R\x03msgB\x06\n" +
	"\x04item\"\x89\x01\n" +
	"\rStreamRequest\x12;\n" +
	"\bcommands\x18\x01 \x03(\v2\x1f.cc.StreamRequest.CommandsEntryR\bcommands\x1a;\n" +
	"\rCommandsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*4\n" +
	"\x04Role\x12\f\n" +
	"\bNOACCESS\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\t\n" +
	"\x05OWNER\x10\x02\x12\t\n" +
	"\x05ADMIN\x10\x03*\x9a\x01\n" +
	"\x06Status\x12\a\n" +
	"\x03NEW\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\v\n" +
	"\aRESOLVE\x10\x02\x12\t\n" +
	"\x05CLOSE\x10\x03\x12\f\n" +
	"\bANSWERED\x10\x04\x12\x12\n" +
	"\x0eCUSTOMER_REPLY\x10\x05\x12\x15\n" +
	"\x11WAITING_FOR_REPLY\x10\x06\x12\v\n" +
	"\aON_HOLD\x10\a\x12\x0f\n" +
	"\vIN_PROGRESS\x10\b\x12\x0e\n" +
	"\n" +
	"ONBOARDING\x10\t*=\n" +
	"\x04Kind\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\x0e\n" +
	"\n" +
	"ADMIN_ONLY\x10\x01\x12\v\n" +
	"\aFOR_BOT\x10\x02\x12\v\n" +
	"\aCOPILOT\x10\x03*\xde\x01\n" +
	"\tEventType\x12\b\n" +
	"\x04PING\x10\x00\x12\x10\n" +
	"\fCHAT_CREATED\x10\x01\x12\x10\n" +
	"\fCHAT_UPDATED\x10\x02\x12\x10\n" +
	"\fCHAT_DELETED\x10\x03\x12\r\n" +
	"\tCHAT_READ\x10\x04\x12\x10\n" +
	"\fMESSAGE_SENT\x10\x05\x12\x13\n" +
	"\x0fMESSAGE_UPDATED\x10\x06\x12\x13\n" +
	"\x0fMESSAGE_DELETED\x10\a\x12\x1b\n" +
	"\x17CHAT_DEPARTMENT_CHANGED\x10\b\x12\x17\n" +
	"\x13CHAT_STATUS_CHANGED\x10\t\x12\x10\n" +
	"\fCHATS_MERGED\x10\n" +
	"2\xf7\x03\n" +
	"\bChatsAPI\x12\x1c\n" +
	"\x06Create\x12\b.cc.Chat\x1a\b.cc.Chat\x12\x1c\n" +
	"\x06Update\x12\b.cc.Chat\x1a\b.cc.Chat\x12\x19\n" +
	"\x03Get\x12\b.cc.Chat\x1a\b.cc.Chat\x123\n" +
	"\x04List\x12\x14.cc.ListChatsRequest\x1a\x15.cc.ListChatsResponse\x126\n" +
	"\x05Count\x12\x15.cc.CountChatsRequest\x1a\x16.cc.CountChatsResponse\x12\x1c\n" +
	"\x06Delete\x12\b.cc.Chat\x1a\b.cc.Chat\x12/\n" +
	"\vSetBotState\x12\x16.cc.SetBotStateRequest\x1a\b.cc.Chat\x12!\n" +
	"\vGetBotState\x12\b.cc.Chat\x1a\b.cc.Chat\x12&\n" +
	"\x10ChangeDepartment\x12\b.cc.Chat\x1a\b.cc.Chat\x12#\n" +
	"\rChangeGateway\x12\b.cc.Chat\x1a\b.cc.Chat\x12\"\n" +
	"\fChangeStatus\x12\b.cc.Chat\x1a\b.cc.Chat\x12!\n" +
	"\n" +
	"MergeChats\x12\t.cc.Merge\x1a\b.cc.Chat\x12!\n" +
	"\tSyncChats\x12\t.cc.Empty\x1a\t.cc.Empty2\x94\x02\n" +
	"\vMessagesAPI\x12\x1d\n" +
	"\x03Get\x12\b.cc.Chat\x1a\f.cc.Messages\x12 \n" +
	"\x04Send\x12\v.cc.Message\x1a\v.cc.Message\x12\"\n" +
	"\x06Update\x12\v.cc.Message\x1a\v.cc.Message\x12\"\n" +
	"\x06Delete\x12\v.cc.Message\x1a\v.cc.Message\x12$\n" +
	"\x04Vote\x12\x0f.cc.VoteRequest\x1a\v.cc.Message\x12'\n" +
	"\x05Polls\x12\x10.cc.PollsRequest\x1a\f.cc.Messages\x12-\n" +
	"\x04List\x12\x17.cc.MessagesListRequest\x1a\f.cc.Messages2\xfe\x01\n" +
	"\bUsersAPI\x12\x19\n" +
	"\x02Me\x12\t.cc.Empty\x1a\b.cc.User\x127\n" +
	"\rFetchDefaults\x12\x18.cc.FetchDefaultsRequest\x1a\f.cc.Defaults\x12$\n" +
	"\tGetConfig\x12\t.cc.Empty\x1a\f.cc.Defaults\x12'\n" +
	"\tSetConfig\x12\f.cc.Defaults\x1a\f.cc.Defaults\x12\x1f\n" +
	"\aResolve\x12\t.cc.Users\x1a\t.cc.Users\x12.\n" +
	"\n" +
	"GetMembers\x12\x15.cc.GetMembersRequest\x1a\t.cc.Users29\n" +
	"\rStreamService\x12(\n" +
	"\x06Stream\x12\x11.cc.StreamRequest\x1a\t.cc.Event0\x01B%Z#github.com/slntopp/core-chatting/ccb\x06proto3"

var (
	file_cc_cc_proto_rawDescOnce sync.Once
	file_cc_cc_proto_rawDescData []byte
)

func file_cc_cc_proto_rawDescGZIP() []byte {
	file_cc_cc_proto_rawDescOnce.Do(func() {
		file_cc_cc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cc_cc_proto_rawDesc), len(file_cc_cc_proto_rawDesc)))
	})
	return file_cc_cc_proto_rawDescData
}

var file_cc_cc_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cc_cc_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_cc_cc_proto_goTypes = []any{
	(Role)(0),                    // 0: cc.Role
	(Status)(0),                  // 1: cc.Status
	(Kind)(0),                    // 2: cc.Kind
	(EventType)(0),               // 3: cc.EventType
	(*Empty)(nil),                // 4: cc.Empty
	(*ChatMeta)(nil),             // 5: cc.ChatMeta
	(*Chat)(nil),                 // 6: cc.Chat
	(*Chats)(nil),                // 7: cc.Chats
	(*Merge)(nil),                // 8: cc.Merge
	(*ListChatsRequest)(nil),     // 9: cc.ListChatsRequest
	(*SetBotStateRequest)(nil),   // 10: cc.SetBotStateRequest
	(*ListChatsResponse)(nil),    // 11: cc.ListChatsResponse
	(*CountChatsRequest)(nil),    // 12: cc.CountChatsRequest
	(*CountChatsResponse)(nil),   // 13: cc.CountChatsResponse
	(*Attachment)(nil),           // 14: cc.Attachment
	(*PollOption)(nil),           // 15: cc.PollOption
	(*PollVote)(nil),             // 16: cc.PollVote
	(*Poll)(nil),                 // 17: cc.Poll
	(*VoteRequest)(nil),          // 18: cc.VoteRequest
	(*Message)(nil),              // 19: cc.Message
	(*Messages)(nil),             // 20: cc.Messages
	(*MessagesListRequest)(nil),  // 21: cc.MessagesListRequest
	(*PollsRequest)(nil),         // 22: cc.PollsRequest
	(*User)(nil),                 // 23: cc.User
	(*Department)(nil),           // 24: cc.Department
	(*Option)(nil),               // 25: cc.Option
	(*Metric)(nil),               // 26: cc.Metric
	(*Defaults)(nil),             // 27: cc.Defaults
	(*Bot)(nil),                  // 28: cc.Bot
	(*Users)(nil),                // 29: cc.Users
	(*FetchDefaultsRequest)(nil), // 30: cc.FetchDefaultsRequest
	(*GetMembersRequest)(nil),    // 31: cc.GetMembersRequest
	(*Event)(nil),                // 32: cc.Event
	(*StreamRequest)(nil),        // 33: cc.StreamRequest
	nil,                          // 34: cc.ChatMeta.DataEntry
	nil,                          // 35: cc.Chat.BotStateEntry
	nil,                          // 36: cc.ListChatsRequest.FiltersEntry
	nil,                          // 37: cc.SetBotStateRequest.StateEntry
	nil,                          // 38: cc.CountChatsRequest.FiltersEntry
	nil,                          // 39: cc.CountChatsResponse.StatusesEntry
	nil,                          // 40: cc.Poll.VotesEntry
	nil,                          // 41: cc.Message.MetaEntry
	nil,                          // 42: cc.User.CcCommandsEntry
	nil,                          // 43: cc.Defaults.MetricsEntry
	nil,                          // 44: cc.Defaults.TemplatesEntry
	nil,                          // 45: cc.Bot.ValuesEntry
	nil,                          // 46: cc.GetMembersRequest.FiltersEntry
	nil,                          // 47: cc.StreamRequest.CommandsEntry
	(*structpb.Struct)(nil),      // 48: google.protobuf.Struct
	(*structpb.Value)(nil),       // 49: google.protobuf.Value
}
var file_cc_cc_proto_depIdxs = []int32{
	19, // 0: cc.ChatMeta.first_message:type_name -> cc.Message
	19, // 1: cc.ChatMeta.last_message:type_name -> cc.Message
	34, // 2: cc.ChatMeta.data:type_name -> cc.ChatMeta.DataEntry
	0,  // 3: cc.Chat.role:type_name -> cc.Role
	5,  // 4: cc.Chat.meta:type_name -> cc.ChatMeta
	1,  // 5: cc.Chat.status:type_name -> cc.Status
	35, // 6: cc.Chat.bot_state:type_name -> cc.Chat.BotStateEntry
	6,  // 7: cc.Chats.chats:type_name -> cc.Chat
	36, // 8: cc.ListChatsRequest.filters:type_name -> cc.ListChatsRequest.FiltersEntry
	37, // 9: cc.SetBotStateRequest.state:type_name -> cc.SetBotStateRequest.StateEntry
	6,  // 10: cc.ListChatsResponse.pool:type_name -> cc.Chat
	38, // 11: cc.CountChatsRequest.filters:type_name -> cc.CountChatsRequest.FiltersEntry
	39, // 12: cc.CountChatsResponse.statuses:type_name -> cc.CountChatsResponse.StatusesEntry
	15, // 13: cc.Poll.options:type_name -> cc.PollOption
	40, // 14: cc.Poll.votes:type_name -> cc.Poll.VotesEntry
	2,  // 15: cc.Message.kind:type_name -> cc.Kind
	41, // 16: cc.Message.meta:type_name -> cc.Message.MetaEntry
	17, // 17: cc.Message.poll:type_name -> cc.Poll
	19, // 18: cc.Messages.messages:type_name -> cc.Message
	48, // 19: cc.User.data:type_name -> google.protobuf.Struct
	42, // 20: cc.User.cc_commands:type_name -> cc.User.CcCommandsEntry
	25, // 21: cc.Metric.options:type_name -> cc.Option
	24, // 22: cc.Defaults.departments:type_name -> cc.Department
	43, // 23: cc.Defaults.metrics:type_name -> cc.Defaults.MetricsEntry
	44, // 24: cc.Defaults.templates:type_name -> cc.Defaults.TemplatesEntry
	28, // 25: cc.Defaults.bot:type_name -> cc.Bot
	45, // 26: cc.Bot.values:type_name -> cc.Bot.ValuesEntry
	23, // 27: cc.Users.users:type_name -> cc.User
	46, // 28: cc.GetMembersRequest.filters:type_name -> cc.GetMembersRequest.FiltersEntry
	3,  // 29: cc.Event.type:type_name -> cc.EventType
	6,  // 30: cc.Event.chat:type_name -> cc.Chat
	19, // 31: cc.Event.msg:type_name -> cc.Message
	47, // 32: cc.StreamRequest.commands:type_name -> cc.StreamRequest.CommandsEntry
	49, // 33: cc.ChatMeta.DataEntry.value:type_name -> google.protobuf.Value
	49, // 34: cc.Chat.BotStateEntry.value:type_name -> google.protobuf.Value
	49, // 35: cc.ListChatsRequest.FiltersEntry.value:type_name -> google.protobuf.Value
	49, // 36: cc.SetBotStateRequest.StateEntry.value:type_name -> google.protobuf.Value
	49, // 37: cc.CountChatsRequest.FiltersEntry.value:type_name -> google.protobuf.Value
	16, // 38: cc.Poll.VotesEntry.value:type_name -> cc.PollVote
	49, // 39: cc.Message.MetaEntry.value:type_name -> google.protobuf.Value
	26, // 40: cc.Defaults.MetricsEntry.value:type_name -> cc.Metric
	49, // 41: cc.GetMembersRequest.FiltersEntry.value:type_name -> google.protobuf.Value
	6,  // 42: cc.ChatsAPI.Create:input_type -> cc.Chat
	6,  // 43: cc.ChatsAPI.Update:input_type -> cc.Chat
	6,  // 44: cc.ChatsAPI.Get:input_type -> cc.Chat
	9,  // 45: cc.ChatsAPI.List:input_type -> cc.ListChatsRequest
	12, // 46: cc.ChatsAPI.Count:input_type -> cc.CountChatsRequest
	6,  // 47: cc.ChatsAPI.Delete:input_type -> cc.Chat
	10, // 48: cc.ChatsAPI.SetBotState:input_type -> cc.SetBotStateRequest
	6,  // 49: cc.ChatsAPI.GetBotState:input_type -> cc.Chat
	6,  // 50: cc.ChatsAPI.ChangeDepartment:input_type -> cc.Chat
	6,  // 51: cc.ChatsAPI.ChangeGateway:input_type -> cc.Chat
	6,  // 52: cc.ChatsAPI.ChangeStatus:input_type -> cc.Chat
	8,  // 53: cc.ChatsAPI.MergeChats:input_type -> cc.Merge
	4,  // 54: cc.ChatsAPI.SyncChats:input_type -> cc.Empty
	6,  // 55: cc.MessagesAPI.Get:input_type -> cc.Chat
	19, // 56: cc.MessagesAPI.Send:input_type -> cc.Message
	19, // 57: cc.MessagesAPI.Update:input_type -> cc.Message
	19, // 58: cc.MessagesAPI.Delete:input_type -> cc.Message
	18, // 59: cc.MessagesAPI.Vote:input_type -> cc.VoteRequest
	22, // 60: cc.MessagesAPI.Polls:input_type -> cc.PollsRequest
	21, // 61: cc.MessagesAPI.List:input_type -> cc.MessagesListRequest
	4,  // 62: cc.UsersAPI.Me:input_type -> cc.Empty
	30, // 63: cc.UsersAPI.FetchDefaults:input_type -> cc.FetchDefaultsRequest
	4,  // 64: cc.UsersAPI.GetConfig:input_type -> cc.Empty
	27, // 65: cc.UsersAPI.SetConfig:input_type -> cc.Defaults
	29, // 66: cc.UsersAPI.Resolve:input_type -> cc.Users
	31, // 67: cc.UsersAPI.GetMembers:input_type -> cc.GetMembersRequest
	33, // 68: cc.StreamService.Stream:input_type -> cc.StreamRequest
	6,  // 69: cc.ChatsAPI.Create:output_type -> cc.Chat
	6,  // 70: cc.ChatsAPI.Update:output_type -> cc.Chat
	6,  // 71: cc.ChatsAPI.Get:output_type -> cc.Chat
	11, // 72: cc.ChatsAPI.List:output_type -> cc.ListChatsResponse
	13, // 73: cc.ChatsAPI.Count:output_type -> cc.CountChatsResponse
	6,  // 74: cc.ChatsAPI.Delete:output_type -> cc.Chat
	6,  // 75: cc.ChatsAPI.SetBotState:output_type -> cc.Chat
	6,  // 76: cc.ChatsAPI.GetBotState:output_type -> cc.Chat
	6,  // 77: cc.ChatsAPI.ChangeDepartment:output_type -> cc.Chat
	6,  // 78: cc.ChatsAPI.ChangeGateway:output_type -> cc.Chat
	6,  // 79: cc.ChatsAPI.ChangeStatus:output_type -> cc.Chat
	6,  // 80: cc.ChatsAPI.MergeChats:output_type -> cc.Chat
	4,  // 81: cc.ChatsAPI.SyncChats:output_type -> cc.Empty
	20, // 82: cc.MessagesAPI.Get:output_type -> cc.Messages
	19, // 83: cc.MessagesAPI.Send:output_type -> cc.Message
	19, // 84: cc.MessagesAPI.Update:output_type -> cc.Message
	19, // 85: cc.MessagesAPI.Delete:output_type -> cc.Message
	19, // 86: cc.MessagesAPI.Vote:output_type -> cc.Message
	20, // 87: cc.MessagesAPI.Polls:output_type -> cc.Messages
	20, // 88: cc.MessagesAPI.List:output_type -> cc.Messages
	23, // 89: cc.UsersAPI.Me:output_type -> cc.User
	27, // 90: cc.UsersAPI.FetchDefaults:output_type -> cc.Defaults
	27, // 91: cc.UsersAPI.GetConfig:output_type -> cc.Defaults
	27, // 92: cc.UsersAPI.SetConfig:output_type -> cc.Defaults
	29, // 93: cc.UsersAPI.Resolve:output_type -> cc.Users
	29, // 94: cc.UsersAPI.GetMembers:output_type -> cc.Users
	32, // 95: cc.StreamService.Stream:output_type -> cc.Event
	69, // [69:96] is the sub-list for method output_type
	42, // [42:69] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_cc_cc_proto_init() }
func file_cc_cc_proto_init() {
	if File_cc_cc_proto != nil {
		return
	}
	file_cc_cc_proto_msgTypes[2].OneofWrappers = []any{}
	file_cc_cc_proto_msgTypes[5].OneofWrappers = []any{}
	file_cc_cc_proto_msgTypes[6].OneofWrappers = []any{}
	file_cc_cc_proto_msgTypes[15].OneofWrappers = []any{}
	file_cc_cc_proto_msgTypes[20].OneofWrappers = []any{}
	file_cc_cc_proto_msgTypes[27].OneofWrappers = []any{}
	file_cc_cc_proto_msgTypes[28].OneofWrappers = []any{
		(*Event_Chat)(nil),
		(*Event_Msg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cc_cc_proto_rawDesc), len(file_cc_cc_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_cc_cc_proto_goTypes,
		DependencyIndexes: file_cc_cc_proto_depIdxs,
		EnumInfos:         file_cc_cc_proto_enumTypes,
		MessageInfos:      file_cc_cc_proto_msgTypes,
	}.Build()
	File_cc_cc_proto = out.File
	file_cc_cc_proto_goTypes = nil
	file_cc_cc_proto_depIdxs = nil
}
