name: Build Python Package

on:
  push:
    branches:
      - master
      - dev
    paths:
      - '.github/workflows/pip.yml'
      - 'python/**'
      - '!python/dist'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
      - name: Build
        working-directory: python
        run: |
          python -m build
      - name: Commit and push
        run: |
          git config --local user.email "slntopp@users.noreply.github.com"
          git config --local user.name "Mikita Iwanowski"
          git add -f python/dist/*
          git commit -m "Update python package"
          git push
          
      